name: llm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.4.26=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.1.1=py310h6a678d5_0
  - icu=73.2=h59595ed_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.8=py310h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py310hcb52e73_6
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.0.30=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.24.3=py310hd5efca6_0
  - numpy-base=1.24.3=py310h8e6c178_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openbabel=3.1.1=py310h956b46e_8
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.0=h7b32b05_1
  - pandas-stubs=2.3.0.250703=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.1=pyhc872135_2
  - pixman=0.46.0=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycairo=1.23.0=py310hd1222b9_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=7_cp310
  - pytorch=2.3.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - reportlab=3.5.67=py310h0edfc0f_1
  - requests=2.32.3=py310h06a4308_1
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - smina=2020.12.10=hd5edb52_1
  - sqlalchemy=2.0.39=py310h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py310h06a4308_1
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py310_cu121
  - torchtriton=2.3.1=py310
  - torchvision=0.18.1=py310_cu121
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - urllib3=2.3.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-kbproto=1.0.7=h5eee18b_1003
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=h5eee18b_1004
  - xorg-xorgproto=2024.1=h5eee18b_0
  - xorg-xproto=7.0.31=h5eee18b_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bio==1.8.0
      - biopython==1.85
      - biothings-client==0.4.1
      - easydict==1.13
      - exceptiongroup==1.3.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - gprofiler-official==1.0.0
      - gpytorch==1.14
      - h11==0.16.0
      - hf-xet==1.1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.31.1
      - jaxtyping==0.3.2
      - joblib==1.5.0
      - jsonlines==4.0.0
      - linear-operator==0.6
      - lmdb==1.6.2
      - loguru==0.7.3
      - multidict==6.4.3
      - mygene==3.2.2
      - nvidia-ml-py==12.570.86
      - nvitop==1.5.0
      - packaging==25.0
      - pandas==2.2.3
      - platformdirs==4.3.8
      - pooch==1.8.2
      - propcache==0.3.1
      - psutil==7.0.0
      - pyg-lib==0.4.0+pt23cu121
      - pytz==2025.2
      - rdkit==2024.9.6
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sniffio==1.3.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch-cluster==1.6.3+pt23cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt23cu121
      - torch-sparse==0.6.18+pt23cu121
      - torch-spline-conv==1.2.2+pt23cu121
      - tqdm==4.67.1
      - transformers==4.51.3
      - wadler-lindig==0.1.5
      - yarl==1.20.0
